載入本章所需套件

In [2]:
# 以下兩行是畫圖用
%matplotlib inline
import matplotlib.pyplot as plt 
# 載入pandas套件
import pandas as pd
import numpy as np

In [3]:
grades_dict={'name':['Alice','Bob','Candy'],
        "math":[98,89,95],
        "english":[95,90,92],}

df_dict=pd.DataFrame(grades_dict)
print("使用dict生成的DataFrame:","\n",df_dict,"\n")

grades_list=[['Alice',98,95],
                ['Bob',89,90],
                ['Candy',95,92]]
df_list=pd.DataFrame(grades_list)
print("使用list生成的DataFrame:","\n",df_list,"\n")
df_list.columns=['name','math','english']
print("使用list生成的DataFrame,並且加入columns:","\n",df_list,"\n")

df_dict.index=['a','b','c']#加入index
df_dict.columns=['student_name','student_math_score','student_englsh']#加入index
print(df_dict,"\n")

df_dict.head(2)

使用dict生成的DataFrame: 
     name  math  english
0  Alice    98       95
1    Bob    89       90
2  Candy    95       92 

使用list生成的DataFrame: 
        0   1   2
0  Alice  98  95
1    Bob  89  90
2  Candy  95  92 

使用list生成的DataFrame,並且加入columns: 
     name  math  english
0  Alice    98       95
1    Bob    89       90
2  Candy    95       92 

  student_name  student_math_score  student_englsh
a        Alice                  98              95
b          Bob                  89              90
c        Candy                  95              92 



student_name  student_math_score  student_englsh
a        Alice                  98              95
b          Bob                  89              90

2-1 創立DataFrame

範例2-1

In [4]:
# {:,:,:,:} 是字典的資料類型
scores = {'Math':[90,50,70,80],
          'English':[60,70,90,50],
          'History':[33,75,88,60]}
print(scores)

# .DataFrame(資料) 將資料類型轉為 DataFrame 類型之指令
df = pd.DataFrame(scores)
df

{'Math': [90, 50, 70, 80], 'English': [60, 70, 90, 50], 'History': [33, 75, 88, 60]}


Math  English  History
0    90       60       33
1    50       70       75
2    70       90       88
3    80       50       60

範例2-2

In [5]:
# .index 為設定 列索引鍵 之指令
df.index= ['Simon','Allen','Jimmy','Peter']
df
#df['Math'].values

array([90, 50, 70, 80], dtype=int64)

2-2 DataFrame裡幾個重要的屬性

範例2-3

In [6]:
df.index

Index(['Simon', 'Allen', 'Jimmy', 'Peter'], dtype='object')

範例2-4

In [7]:
df.columns

Index(['Math', 'English', 'History'], dtype='object')

範例2-5

In [8]:
df.values

array([[90, 60, 33],
       [50, 70, 75],
       [70, 90, 88],
       [80, 50, 60]], dtype=int64)

範例2-6

In [9]:
df.shape

(4, 3)

範例2-6 改

In [10]:
Rows,Columns = df.shape
print("Rows:",Rows)
print("Columns:",Columns)

Rows: 4
Columns: 3


範例2-7 df的資料都是int64
df.dtype 是一个通常用於查看DataFrame中列的數據類型的屬性

In [11]:
df.dtypes

Math       int64
English    int64
History    int64
dtype: object

2-3 一維和二維資料的差異

範例2-8

In [12]:
# 在Pandas中，一維的資料叫做 Series
# pd.Series(資料) 是將資料類型轉換為 Series資料類型 的指令
s=pd.Series([1,2,3])
print(f's的維度 {s.shape}')
s

s的維度 (3,)


0    1
1    2
2    3
dtype: int64

範例2-9

In [13]:
# 在Pandas中，二維的資料叫做 DataFrame
d=s.to_frame()
print(f'd的維度 {d.shape}')
d

d的維度 (3, 1)


0
0  1
1  2
2  3

範例2-10 轉置

In [14]:
t=d.T
print(f't的維度 {t.shape}')
t

t的維度 (1, 3)


0  1  2
0  1  2  3

範例2-11(注意"print(f'np_a的維度 {np_a.shape}')"內容)

In [15]:
# np.array(資料) 將資料類型轉為 數組 類型之指令
List_A = [1,2,3] # 陣列 的資料類型
np_a =np.array(List_A)  # 數組 的資料類型
print(List_A)
print(np_a)
print(f'np_a的維度 {np_a.shape}')
np_a,type(np_a)

[1, 2, 3]
[1 2 3]
np_a的維度 (3,)


(array([1, 2, 3]), numpy.ndarray)

範例2-12

In [16]:
# .reshape(新維度) 資料維度 轉換指令
np_a2 = np_a.reshape(3,1)
print(np_a2)
print(f'np_a2的維度 {np_a2.shape}')
np_a2

[[1]
 [2]
 [3]]
np_a2的維度 (3, 1)


array([[1],
       [2],
       [3]])

範例2-13(.reshape(-1,1):第一個參數-1表列數電腦決定，第二個參數1表行數一行)

In [17]:
np_a.reshape(-1,1).shape
np_a

array([1, 2, 3])

範例2-14

In [18]:
np_a.reshape(1,-1).shape,np_a

((1, 3), array([1, 2, 3]))

範例2-15

In [19]:
List_B = [[1,2,3],[4,5,6]] # 二維陣列 的資料類型
np_a3 = np.array(List_B) # 轉成 二維數組 的資料類型
print("List_B:")
print(List_B)
print("np_a3:")
print(np_a3)
np_a3.shape

List_B:
[[1, 2, 3], [4, 5, 6]]
np_a3:
[[1 2 3]
 [4 5 6]]


(2, 3)

範例2-16

In [20]:
np_a2.reshape(-1).shape

(3,)

範例2-17(二維array轉一維)

In [21]:
np_a2.ravel().shape

(3,)

2-4 NaN介紹

範例2-18

In [22]:
import numpy as np
np.NaN == np.NaN

False

範例2-19

In [23]:
# 用 pd.isnull(A) 指令檢查 資料A 是否是遺漏值
pd.isnull(np.NaN)

True

範例2-20

In [24]:
# 用 pd.notnull(A) 指令檢查 資料A 是否不是遺漏值
pd.notnull(np.NaN)

False

範例2-21

In [25]:
scores = {'Math':[90,50,70,80],
          'Eng lish':[60,70,90,50],
          'History':[33,np.nan,np.nan,60]}

df = pd.DataFrame(scores, index=['Simon','Allen','Jimmy','Peter'])
df

Math  Eng lish  History
Simon    90        60     33.0
Allen    50        70      NaN
Jimmy    70        90      NaN
Peter    80        50     60.0

範例2-21 改

In [26]:
scores = {'Math':[90,50,70,80],
          'English':[60,70,90,50],
          'History':[33,np.nan,np.nan,60]}

df = pd.DataFrame(scores)
df.index = ['Simon','Allen','Jimmy','Peter']
df

Math  English  History
Simon    90       60     33.0
Allen    50       70      NaN
Jimmy    70       90      NaN
Peter    80       50     60.0

In [27]:
# 在 DataFrame 和 array 的資料類型中， .sum() 為計算總和值的指令
df.sum()

Math       290.0
English    270.0
History     93.0
dtype: float64

範例2-22

In [28]:
df.isnull()

Math  English  History
Simon  False    False    False
Allen  False    False     True
Jimmy  False    False     True
Peter  False    False    False

範例2-23

In [29]:
df.isnull().sum()

Math       0
English    0
History    2
dtype: int64

範例2-24

In [30]:
df.isnull().sum().sum()

2

範例2-25檢查某列有無null
axis見2-6

In [31]:
df.isnull().any(axis=1)

Simon    False
Allen     True
Jimmy     True
Peter    False
dtype: bool

範例2-26因為加了isnull所以df內只顯示有null的

In [32]:
df[df.isnull().any(axis=1)]

Math  English  History
Allen    50       70      NaN
Jimmy    70       90      NaN

2-7節 篩選資料

In [33]:
df[[False,True,True,False]]

Math  English  History
Allen    50       70      NaN
Jimmy    70       90      NaN

2-5 如何定位和讀取 DataFrame 裡的元素

先回顧 df

In [34]:
df

Math  English  History
Simon    90       60     33.0
Allen    50       70      NaN
Jimmy    70       90      NaN
Peter    80       50     60.0

範例2-27 因為是一欄的結果，所以回傳值是一維的 Series

In [35]:
# 
df['English']

Simon    60
Allen    70
Jimmy    90
Peter    50
Name: English, dtype: int64

範例2-28

In [36]:
# 欄位名稱有空格時，此方法不適用
df.English#,df.Math

Simon    60
Allen    70
Jimmy    90
Peter    50
Name: English, dtype: int64

範例2-29

In [37]:
# 取兩個以上的欄位值，用串列將欄位名稱包覆
# 因為是多欄的結果，所以回傳值是二維的 Series
df[['English','Math']]

English  Math
Simon       60    90
Allen       70    50
Jimmy       90    70
Peter       50    80

範例2-30 與2-28不同

In [38]:
# 當DataFrame看見索引欄是串列時，它就會預設資料是二維的DataFrame
df[['English']]

English
Simon       60
Allen       70
Jimmy       90
Peter       50

範例2-31 索引列名稱

In [39]:
# .loc 採用 索引列名稱 擷取資料
# 回傳的資料是一維的 Series
# 以下範例為擷取 Simon列 的資料
df.loc['Simon']

Math       90.0
English    60.0
History    33.0
Name: Simon, dtype: float64

範例2-32 索引列位置

In [40]:
# .iloc 採用 索引列位置 擷取資料
# 以下範例為擷取 第0列 的資料
df.iloc[0]

Math       90.0
English    60.0
History    33.0
Name: Simon, dtype: float64

In [41]:
# .iloc 採用 資料位置 擷取資料
# 以下範例為擷取 第0列,第1行 的資料
df.iloc[0,1]

60

In [42]:
# .iloc 採用 資料位置 擷取資料
# 以下範例為擷取 第-4列,第-2行 的資料
"""
df.iloc[3,0]=101
print("peter修改後:")
"""
print(df,"\n")
df.iloc[-4,-2]

       Math  English  History
Simon    90       60     33.0
Allen    50       70      NaN
Jimmy    70       90      NaN
Peter    80       50     60.0 



60

In [43]:
# !!! 重要 !!!
# 此部分之內容與 Homework2 相關
# 請將 df 中，位置[0,1]之成績資料修改為 70 分
# 並將結果輸出
df.iloc[0,1]=70
df

Math  English  History
Simon    90       70     33.0
Allen    50       70      NaN
Jimmy    70       90      NaN
Peter    80       50     60.0

In [44]:
# !!! 重要 !!!
# 此部分之內容與 Homework2 相關
# 請將 df 中，NaN之成績資料修改為 該科目之平均分數
# 並將結果輸出
df.iloc[1,2]=(df.iloc[0,2]+df.iloc[3,2])/2
df.iloc[2,2]=(df.iloc[0,2]+df.iloc[3,2])/2

#df.iloc[1,2]=df.iloc[:,2].mean()
#df.iloc[2,2]=df.iloc[:,2].mean()

"""
for i in range(0,len(df)):
    for j in range(0,len(df.columns)):
        if pd.isnull(df.iloc[i,j]):
            df.iloc[i,j]=df.iloc[:,j].mean()
"""
df

Math  English  History
Simon    90       70     33.0
Allen    50       70     46.5
Jimmy    70       90     46.5
Peter    80       50     60.0

df[ : ]使用方式

In [45]:
# .iloc 採用 資料位置 擷取資料
# 以下範例為擷取 ":"(所有列),第1行 的資料
df.iloc[:,1]

Simon    70
Allen    70
Jimmy    90
Peter    50
Name: English, dtype: int64

In [46]:
# .iloc 採用 資料位置 擷取資料
# 以下範例為擷取 第0列,所有行 的資料
df.iloc[0,:]

Math       90.0
English    70.0
History    33.0
Name: Simon, dtype: float64

In [47]:
# .iloc 採用 資料位置 擷取資料
# 以下範例為擷取 第0列至第1列,第1行至第2行 的資料
df.iloc[0:2,1:3]

English  History
Simon       70     33.0
Allen       70     46.5

In [48]:
# 當DataFrame看見索引列是串列時，它就會預設資料是二維的DataFrame
df.loc[['Simon']]

Math  English  History
Simon    90       70     33.0

In [49]:
# 當DataFrame看見索引列是串列時，它就會預設資料是二維的DataFrame
df.iloc[[0]]

Math  English  History
Simon    90       70     33.0

範例2-33

In [50]:
# 取兩個以上的索引列值，用串列將索引列名稱包覆
# 回傳的資料是二維的 DataFrame
df.loc[['Jimmy','Simon']]

Math  English  History
Jimmy    70       90     46.5
Simon    90       70     33.0

範例2-34

In [51]:
# 在串列中，可以用 索引列座標 取代 索引列名稱
# 在df中，Jimmy是第2列，Simon是第0列
df.iloc[[2,0]]

Math  English  History
Jimmy    70       90     46.5
Simon    90       70     33.0

範例2-35

In [52]:
df.iloc[-2:]#位置-2之後的

Math  English  History
Jimmy    70       90     46.5
Peter    80       50     60.0

In [53]:
df.iloc[:-2]

Math  English  History
Simon    90       70     33.0
Allen    50       70     46.5

範例2-36

In [54]:
df.loc[:,'Math']

Simon    90
Allen    50
Jimmy    70
Peter    80
Name: Math, dtype: int64

範例2-37

In [55]:
df.loc[['Jimmy','Simon']][['English','History']]

English  History
Jimmy       90     46.5
Simon       70     33.0

範例2-38

In [56]:
df.loc[['Jimmy','Simon'],['English','History']]

English  History
Jimmy       90     46.5
Simon       70     33.0

範例2-39

In [57]:
df.loc[:,'English':'History']

English  History
Simon       70     33.0
Allen       70     46.5
Jimmy       90     46.5
Peter       50     60.0

2-6 介紹 axis 的概念 
axis=0表axis='row'

範例2-40 axis='row'表每個row計算df.mean

In [58]:
df['個人平均'] = df.mean(axis=1)
df

Math  English  History       個人平均
Simon    90       70     33.0  64.333333
Allen    50       70     46.5  55.500000
Jimmy    70       90     46.5  68.833333
Peter    80       50     60.0  63.333333

範例2-41 axis=1表axis='column'

In [59]:
#axis='column'表每個column計算df.mean
df.loc['各科平均'] = df.mean(axis=0)
df

Math  English  History       個人平均
Simon  90.0     70.0     33.0  64.333333
Allen  50.0     70.0     46.5  55.500000
Jimmy  70.0     90.0     46.5  68.833333
Peter  80.0     50.0     60.0  63.333333
各科平均   72.5     70.0     46.5  63.000000

2-7 篩選資料

範例2-42

In [60]:
# 如同範例 2-26
bool_v = [True,True,False,False,False] 
df[bool_v]

Math  English  History       個人平均
Simon  90.0     70.0     33.0  64.333333
Allen  50.0     70.0     46.5  55.500000

範例2-43

In [61]:
bool_v = df['Math'] >= 60
bool_v

Simon     True
Allen    False
Jimmy     True
Peter     True
各科平均      True
Name: Math, dtype: bool

範例2-44

In [62]:
df[bool_v]

Math  English  History       個人平均
Simon  90.0     70.0     33.0  64.333333
Jimmy  70.0     90.0     46.5  68.833333
Peter  80.0     50.0     60.0  63.333333
各科平均   72.5     70.0     46.5  63.000000

2-8 用apply()讓資料處理更簡單

範例2-45

In [63]:
s = pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

範例2-46

In [64]:
s.apply(lambda x: x+1 if (x%2)==1 else x-1)

0    2
1    1
2    4
3    3
4    6
dtype: int64

In [65]:
s.apply(lambda x: x if (x%3)==1 else x+1 if (x%3)==2 else x-1)

0    1
1    3
2    2
3    4
4    6
dtype: int64

In [66]:
df.apply(max, axis=1)

Simon    90.0
Allen    70.0
Jimmy    90.0
Peter    80.0
各科平均     72.5
dtype: float64

範例2-47

In [67]:
scores = {'Math':[900,50,730,80],
          'History':[33,75,np.NaN,np.NaN]}
df = pd.DataFrame(scores, index = ['Simon','Allen','Jimmy','Peter'])
df

Math  History
Simon   900     33.0
Allen    50     75.0
Jimmy   730      NaN
Peter    80      NaN

範例2-48

In [68]:
df.apply(max)

Math       900.0
History     75.0
dtype: float64

範例2-49

In [69]:
df.apply(max, axis=1)

Simon    900.0
Allen     75.0
Jimmy    730.0
Peter     80.0
dtype: float64